name: "Hello World"
description: "Greet someone and record the time"
inputs:
  title-regex:
    description: "Title regex to match"
    required: true
    default: '^(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|deps){1}(\([\w-\.]+\))?(!)?:\ ([\w\ ])+([\s\S]*)\[(MT|MI|INT|CT|HF|DB|RI|MN)-\d+\]'
  branch-regex:
    description: "Title regex to match"
    required: true
    default: '(MT|MI|INT|CT|HF|DB|RI|MN)-\d+'
outputs:
  time: # id of output
    description: "The time we greeted you"
runs:
  using: "node12"
  main: "dist/index.js"
