on: [push, pull_request]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Request Lint
        uses: ./