on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    name: Pull Request Linter
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Pull Request Lint
        uses: ./